### ISSUE TITLE
Using with Docker

### ISSUE THREAD

**Issue by leem32** [vkuznecovas/mouthful#93]
I want to get Mouthful working in Docker, but have a couple of questions.

So far I've created a file in my web root and added the below code:

     <div id="mouthful-comments" data-url="http://10.0.0.0:8080"></div>
     <script src="http://10.0.0.0:8080/client.js"></script>

Then I cloned the repo into the default repo download directory of Centos 7.
Then I built the Docker image with `docker build -t mouthful .`

And that's as far as I've got because I don't quite understand the next `Run the image` part.

Do I just need to run the below code from anywhere or do I need to be in the web root dir e.g `/var/www/html/`
`docker run -d \
    --name mouthful \
    -v $(pwd)/data:/app/data
    -p 8080:8080
    vkuznecovas/mouthful`

Also the cofig.json file `docker run --rm vkuznecovas/mouthful cat /app/data/config.json > config.json`
This will create a file named config.json in your host machine, you can edit it as you please. Make sure it is present in the data folder before running the docker image, read the note in run the image.

I don't understand the part 'make sure it's present in the data folder'. Where will I find the data folder at this point. I haven't run the image yet so I'm a little confused. Does the data folder need to be in my web root at some point?  

Sorry for these noob questions. I'm brand new to Docker and only installed it for Mouthful.

Thanks :)

**Comment by vkuznecovas** [comment]
Right, so basicly the mouthful instance requires a config.json file. The config file must be available to the docker container in order for the mouthful running inside it to understand what settings you want to run mouthful under.  

The mouthful docker image already comes with a "default" config.json, which is placed inside the docker container and can be extracted via the following command `docker run --rm vkuznecovas/mouthful cat /app/data/config.json > config.json`. This will copy the config file from the docker container, to your host machine. After running this you should have the config.json in your current directory. This would give you a baseline config file to play with.

The mouthful container stores the config.json and the database file inside the container, in a directory `/app/data`. We can instruct mouthful container to instead use a host system directory for the `/app/data`. To do so, we use the docker run's -v flag.  

In your case, I'd recommend you to create a directory in your host machine, where you'd like to store mouthfuls' config and (if you're gonna use sqlite) database file. Let's say you'll put the config in `/var/mouthful/config.json`. You can then instruct docker to use this directory instead of the containers internal `/app/data` by running the container with a -v flag, like so `docker run -d \ --name mouthful \ -v /var/mouthful/:/app/data -p 8080:8080 vkuznecovas/mouthful`. Then, the running docker container will use the config from hosts `/var/mouthful/config.json`. You should have a mouthful instance running now, on localhost, at port 8080.

At no point in time you actually need to do anything `/var/www/html/`. 

Please let me know if I've made this clearer for you, and do ask if you got more questions. I'm super glad you decided to give mouthful a try!

**Comment by leem32** [comment]
Thanks for the comprehensive response. It's helped me understand how Docker works.

I've created the directory /var/mouthful and placed the config.json file into that directory.

Then I ran the code: `docker run -d \ --name mouthful \ -v /var/mouthful/:/app/data -p 8080:8080 vkuznecovas/mouthful`, but I'm getting an error e.g `docker: invalid reference format.`.
Any ideas? I've tried as sudo user but get the same result.

**Comment by vkuznecovas** [comment]
my bad, remove the backslashes like so `docker run -d --name mouthful -v /var/mouthful/:/app/data -p 8080:8080 vkuznecovas/mouthful`

**Comment by vkuznecovas** [comment]
do a `docker logs 4a0ee982737b`. It probably exited due to some reason. Most likely the default admin moderation password wink wink nudge nudge

**Comment by leem32** [comment]
I checked the docker log and I have the message:

      panic: Please change the config.Moderation.AdminPassword value in config. Do not leave the default 
      there
      goroutine 1 [running]:
      main.main()
        /go/src/github.com/vkuznecovas/mouthful/main.go:82 +0x864

I had already changed the moderation password but it contained a special character so I've taken that out.

I've reloaded the web page, but still no change. Do I need to reload the container now I've changed the config.json? How would I do that?

I tried the run command again but got an error:

    docker: Error response from daemon: Conflict. The container name "/mouthful" is already in use by 
    container...

Running the command `docker container ls` still shows Mouthful is not running.

**Comment by vkuznecovas** [comment]
do a `docker ps` it will list the containers. Take the mouthful container id, and do a `docker restart {id}`.

**Comment by vkuznecovas** [comment]
You'll have to modify the docker file. I don't think there's a way to change it at run time.

**Comment by vkuznecovas** [comment]
Actually that's wrong. You can pass in --user {userid} to the docker run command. So create a user on your centos, and pass the id on docker run via --user!

**Comment by leem32** [comment]
OK, thanks. I'll give that a try.
